[project]
name = "mcp-example"
version = "0.1.0"
description = "An example of how to run a MCP server in Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.12.2",
]
