name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install UV
        uses: astral-sh/setup-uv@v2
        with:
          version: latest

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run black
        run: uv run black --check .

      - name: Run isort
        run: uv run isort --check-only .

      - name: Run flake8
        run: uv run flake8 .

      - name: Run mypy
        run: uv run mypy .
